### ISSUE TITLE
La version 2.0 de la CC-BY-SA n'est pas adaptée aux bases de données (la V 4.0 oui).

### ISSUE THREAD

**Issue by camillem** [skhaen/dataseeds#1]
Bonjour,
Vous indiquez sur la page d'accueil que "la base de données en elle même serait sous Creative Commons BY:SA." avec un lien vers la version 2.0 de la licence. 
Cette version n'est pas adaptée aux bases de données, contrairement à la version 4.0 dont la rédaction les prend explicitement en compte. (cf  https://creativecommons.org/licenses/by-sa/4.0/legalcode notamment la section 4).
En revanche, je ne pense pas qu'elle ait déjà été traduite en français.
HTH, 
Camille

**Comment by skhaen** [comment]
C'est corrigé, merci pour le retour :)
